#pragma kernel Generate
#include "PlanetGeneratorTools.compute"
#include "NoiseS3DGPU.compute"

float radius;

[numthreads(1, 1, 1)]
void Generate (uint3 id : SV_DispatchThreadID) {

	// Get vertex.
	int index = GetIndex(id);
	float3 vertex = vertices[index];

	// Determine height.
	float height = Noise(vertex) * 0.05f;

	// Apply height.
	vertex *= radius + height * radius;
	vertices[index] = vertex;

}
