#pragma kernel ComputeSphere

int3 size;
RWStructuredBuffer<float4> points;

struct Value {
	int3 index;
	float4 p;
};

int GetIndex(uint3 id) {
	// x + y*WIDTH + z*WIDTH*DEPTH
	return id.x + size.x * (id.y + size.y * id.z);
}

[numthreads(1, 1, 1)]
void ComputeSphere (uint3 id : SV_DispatchThreadID) {

	float4 p;
	p.x = (float)id.x;
	p.y = (float)id.y;
	p.z = (float)id.z;

	{

		// TODO:  code for sphere
		p.w = 0;

	}

	points[GetIndex(id)] = p;
	return;

}
